# Generated by Django 3.2.12 on 2022-02-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_board', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('player_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
